//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElementIoT.Particle.Operational.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CommonErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CommonErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ElementIoT.Particle.Operational.Resource.CommonErrorMessages", typeof(CommonErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was a problem while trying to get the command from the action parameters.  Either it was not provided or it was provided under a different parameter name that is not the default name..
        /// </summary>
        public static string Error_CommandInputMissing {
            get {
                return ResourceManager.GetString("Error_CommandInputMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ther was a problem while trying to parse the command from the request. Either the type is incorrect or it was provided under a different parameter name that is not the default name..
        /// </summary>
        public static string Error_CommandTypeInvalid {
            get {
                return ResourceManager.GetString("Error_CommandTypeInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error while trying to parse the correlation Id from the header..
        /// </summary>
        public static string Error_CorrelationIdParsingUnsuccessful {
            get {
                return ResourceManager.GetString("Error_CorrelationIdParsingUnsuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key cannot be set to type&apos;s default value..
        /// </summary>
        public static string Error_DefaultKey {
            get {
                return ResourceManager.GetString("Error_DefaultKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was a problem trying to set the correlation Id in the header of the request..
        /// </summary>
        public static string Error_SetCorrelationHeader {
            get {
                return ResourceManager.GetString("Error_SetCorrelationHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error while trying to execute the requested action..
        /// </summary>
        public static string Error_Unhandled_Exception {
            get {
                return ResourceManager.GetString("Error_Unhandled_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No user associated with the executing action..
        /// </summary>
        public static string Error_User_Missing {
            get {
                return ResourceManager.GetString("Error_User_Missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provided input was invalid.  Fix the validation errors and try your request again..
        /// </summary>
        public static string Validation_Invalidinput {
            get {
                return ResourceManager.GetString("Validation_Invalidinput", resourceCulture);
            }
        }
    }
}
