using System;

namespace ElementIoT.Particle.Operational.Utility
{
    public class KeyGenUtility
    {
        #region Fields

        private static readonly DateTime BASE_DATE = new DateTime(2018, 1, 1, 0, 0, 0);

        #endregion

        #region Properties
        #endregion

        #region Constructors
        #endregion

        #region Methods

        /// <summary>
        /// Generates a new base 64 string key.
        /// </summary>
        /// <remarks>
        /// Key is generated by taking the number of miliseconds between a base date and the current date, then betting the base 64 string
        /// </remarks>
        /// <returns></returns>
        public static string GenerateBase64Key()
        {
            string code = DateTime.UtcNow.Subtract(BASE_DATE).Ticks.ToString();

            var codeBytes = System.Text.Encoding.UTF8.GetBytes(code);
            var codeKey = Convert.ToBase64String(codeBytes).Replace("=", string.Empty);

            return codeKey;
        }

        #endregion
    }
}
